In [1]:
import numpy as np

# Creating Numpy Arrays

In [2]:
#np.array
n=np.array([1,2,3])
print(n) #1D or vector
print(type(n))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D
n1=np.array([[1,2,3],[3,2,1]])
print(n1) #2D or matrix

[[1 2 3]
 [3 2 1]]


In [4]:
#3D
n2=np.array([[[1,2],[3,4]],[[4,3],[2,1]]])
print(n2) 

[[[1 2]
  [3 4]]

 [[4 3]
  [2 1]]]


In [5]:
# dtype
n3=np.array([1,2,3],dtype=float)
print(n3)

[1. 2. 3.]


In [6]:
#np.arange -->same like range() in python
np.arange(1,11) #last value excluded
'np.arange(1,11,2)'

'np.arange(1,11,2)'

In [7]:
#np.arange with reshape --->converting given one Dimension to other Dimension
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
#np.ones 
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
#np.zeros()
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
#np.random
np.random.random((3,4))

array([[0.37152208, 0.29246028, 0.06065628, 0.11410963],
       [0.26467796, 0.63179497, 0.19468014, 0.4587636 ],
       [0.66187018, 0.58115527, 0.76724935, 0.51611958]])

In [11]:
#np.linspace --->linear space
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [13]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#np.eye
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [18]:
#np.full
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

# Array Attributes

In [33]:
a1=np.arange(10)  #vector
a2=np.arange(12).reshape(3,4) #matrix
a3=np.arange(8).reshape(2,2,2) #tensor

In [22]:
#ndim -->numder of dimensions
'a1.ndim'
a3.ndim

3

In [34]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [37]:
#size -->numder of items 
a1.size
a2.size

12

In [41]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	numpy-fundamental.ipynb

nothing added to commit but untracked files present (use "git add" to track)
