In [1]:
import numpy as np

# Creating Numpy Arrays

In [2]:
#np.array
n=np.array([1,2,3])
print(n) #1D or vector
print(type(n))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D
n1=np.array([[1,2,3],[3,2,1]])
print(n1) #2D or matrix

[[1 2 3]
 [3 2 1]]


In [4]:
#3D
n2=np.array([[[1,2],[3,4]],[[4,3],[2,1]]])
print(n2) 

[[[1 2]
  [3 4]]

 [[4 3]
  [2 1]]]


In [5]:
# dtype
n3=np.array([1,2,3],dtype=float)
print(n3)

[1. 2. 3.]


In [6]:
#np.arange -->same like range() in python
np.arange(1,11) #last value excluded
'np.arange(1,11,2)'

'np.arange(1,11,2)'

In [7]:
#np.arange with reshape --->converting given one Dimension to other Dimension
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
#np.ones 
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
#np.zeros()
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
#np.random
np.random.random((3,4))

array([[0.37152208, 0.29246028, 0.06065628, 0.11410963],
       [0.26467796, 0.63179497, 0.19468014, 0.4587636 ],
       [0.66187018, 0.58115527, 0.76724935, 0.51611958]])

In [11]:
#np.linspace --->linear space
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [13]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#np.eye
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [18]:
#np.full
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

# Array Attributes

In [33]:
a1=np.arange(10)  #vector
a2=np.arange(12).reshape(3,4) #matrix
a3=np.arange(8).reshape(2,2,2) #tensor

In [22]:
#ndim -->numder of dimensions
'a1.ndim'
a3.ndim

3

In [34]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [37]:
#size -->numder of items 
a1.size
a2.size

12

In [51]:
#itemsize
a1.itemsize  #memory occupied -->4 bytes

4

In [53]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


# changing Datatypes

In [62]:
#astype--->saves memory space
a1.dtype #int32
#a1.astype('int8') 
a1.astype(np.int8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

# Array operations

In [66]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [68]:
#arithmetic
a1*2      


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [71]:
#relational
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
#arithmetic
a1+a2  #element-wise addition

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [76]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

# Array Functions

In [79]:
a1=np.random.random(9).reshape(3,3)
a2=np.round(a1*100)

array([[13.,  1., 69.],
       [ 0., 47., 37.],
       [44., 21., 95.]])

In [89]:
#min/mx/sum/prod
'a2.min()'
a2.min(axis=1) # axis= 0 (col) or 1 (row)
"np.min(a2,axis=1)
#a2.max()
#a2.sum()
#a3.prod()

array([ 1.,  0., 21.])

In [97]:
#mean/median/std/var
np.mean(a1,axis=1)
np.median(a1,axis=1)
#np.std(a1,axis=0)
#np.var(a1,axis=0)

array([0.13383944, 0.36926273, 0.44014391])

In [98]:
# trigonomoetric functions
np.sin(a1)

array([[0.13344022, 0.01393633, 0.63270105],
       [0.00494209, 0.4552409 , 0.36092796],
       [0.42606966, 0.20789611, 0.81182164]])

In [102]:
# Dot product >
a1=np.arange(8).reshape(4,2)
a2=np.arange(8).reshape(2,4)

In [103]:
np.dot(a1,a2)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47],
       [28, 41, 54, 67]])

In [106]:
#np.log and np.exponents
np.log(a2)
np.exp(a1)

C:\Users\aishw\AppData\Local\Temp\ipykernel_15148\230371989.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03]])

In [118]:
#round/floor/ceil
r=np.random.random((3,3))*100
np.floor(r)
np.ceil(r)

array([[33., 75., 41.],
       [92., 70., 88.],
       [99., 50., 83.]])

# indexing and slicing

In [125]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [132]:
a1[0] # a1[-10]

0

In [134]:
a2[0][1] #2d indexing

1

In [137]:
a2[1,2]

6

In [141]:
a3[1,1,1] #3d indexing

7

In [143]:
a1[2:5] #slicing

array([2, 3, 4])

In [147]:
a2[ : ,: 2] 

array([[0, 1],
       [4, 5],
       [8, 9]])

In [150]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
a3[0,1,:]

array([3, 4, 5])

In [157]:
a3[1,:,1]

array([10, 13, 16])

In [158]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [172]:
a3[: :2,0,: :2]

array([[ 0,  2],
       [18, 20]])

# Iterating


In [176]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [178]:
a2
for i in a2:
    print(i)  

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [179]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [180]:
#np.nditer coverts 3D to 1D
for i in np.nditer(a3): 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# reshaping

-reshape
-Transpose
-ravel

In [181]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
#np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [185]:
#ravel --->converts to 1D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# stacking

In [187]:
#horizontal stacking
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [195]:
s=np.hstack((a1,a2))
s

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [192]:
#vertical stacking
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting 

In [196]:
#horizontal splitting
s

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [199]:
np.hsplit(s,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.vsplit(