In [1]:
import numpy as np

# Mesgrids

# useful functions

In [4]:
#np.sort 
a=np.random.randint(1,100,15)
a

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [12]:
np.sort(a)[::-1] # returns as an sorted array

array([95, 70, 69, 66, 66, 57, 53, 51, 50, 43, 33, 31, 15, 15, 14])

In [8]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[32, 63, 93, 82],
       [77,  7, 55, 80],
       [ 3, 47, 16, 45],
       [55, 31, 49, 82],
       [96, 98, 39, 42],
       [71, 65, 89, 50]])

In [10]:
np.sort(b,axis=0) 

array([[ 3,  7, 16, 42],
       [32, 31, 39, 45],
       [55, 47, 49, 50],
       [71, 63, 55, 80],
       [77, 65, 89, 82],
       [96, 98, 93, 82]])

In [148]:
#np.argsort()
b

array([[79, 66, 67, 75],
       [63, 79, 74, 69],
       [60, 80, 88, 62]])

In [149]:
np.argsort(b,axis=0)

array([[2, 0, 0, 2],
       [1, 1, 1, 1],
       [0, 2, 2, 0]], dtype=int64)

# np.select()

In [ ]:
#used to apply multiple conditions to an array and returns based on which condtion is true
#np.select(condtions,choices,default=0)


In [151]:
x=np.array([10,20,30,40,55,80])
condtions=[x<20,(x>=20) &(x<50),x>=50]
choices=["Low","Medium","High"]
np.select(condtions,choices)

array(['Low', 'Medium', 'Medium', 'Medium', 'High', 'High'], dtype='<U6')

In [14]:
#np.append
np.append(a,200)


array([ 51,  31,  69,  15,  57,  66,  50,  70,  95,  33,  66,  53,  43,
        15,  14, 200])

In [22]:
b
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[32., 63., 93., 82.,  1.],
       [77.,  7., 55., 80.,  1.],
       [ 3., 47., 16., 45.,  1.],
       [55., 31., 49., 82.,  1.],
       [96., 98., 39., 42.,  1.],
       [71., 65., 89., 50.,  1.]])

In [23]:
#np.concatenate
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(b)

[[0 1 2]
 [3 4 5]]
[[32 63 93 82]
 [77  7 55 80]
 [ 3 47 16 45]
 [55 31 49 82]
 [96 98 39 42]
 [71 65 89 50]]


In [26]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
#np.unique
c=np.array([1,2,2,3,4,5,6,7,3,3,2])

In [28]:
np.unique(c)

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
#np.expand_dims
c #1D 

array([1, 2, 2, 3, 4, 5, 6, 7, 3, 3, 2])

In [31]:
np.expand_dims(c,axis=0)  #2D

array([[1, 2, 2, 3, 4, 5, 6, 7, 3, 3, 2]])

# np.where

In [33]:
# returns te indices of elemetns in an imput array where the given condtion is satisfied

In [34]:
a

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [36]:
#find all the indiced with value greater than 50
np.where(a>50)

array([51, 69, 57, 66, 70, 95, 66, 53])

In [37]:
#Replace all values >50
#np.where(conditon,true,false)
np.where(a>50,0,a)


array([ 0, 31,  0, 15,  0,  0, 50,  0,  0, 33,  0,  0, 43, 15, 14])

In [38]:
# np.argmax() >>>indexpostion of max value
np.argmax(a)

8

In [42]:
b

array([[32, 63, 93, 82],
       [77,  7, 55, 80],
       [ 3, 47, 16, 45],
       [55, 31, 49, 82],
       [96, 98, 39, 42],
       [71, 65, 89, 50]])

In [41]:
np.argmax(b,axis=1) 

array([2, 3, 1, 3, 1, 2], dtype=int64)

In [44]:
#np.argmin()
np.argmin(a)

14

# np.cumsum()

In [ ]:
#when we wnat to compute the cumulative sum of array elements over a given axis

In [45]:
a #1D

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [46]:
np.cumsum(a)

array([ 51,  82, 151, 166, 223, 289, 339, 409, 504, 537, 603, 656, 699,
       714, 728])

In [47]:
np.cumsum(b,axis=0)

array([[ 32,  63,  93,  82],
       [109,  70, 148, 162],
       [112, 117, 164, 207],
       [167, 148, 213, 289],
       [263, 246, 252, 331],
       [334, 311, 341, 381]])

# np.cumprod()

In [48]:
np.cumprod(a) #1D

array([         51,        1581,      109089,     1636335,    93271095,
        1860924974, -1443031812,  2066988264, -1204610536, -1097442024,
         583270448,   848562672,  2128456528,  1862076848,   299272096])

In [50]:
np.cumprod(b,axis=0)

array([[         32,          63,          93,          82],
       [       2464,         441,        5115,        6560],
       [       7392,       20727,       81840,      295200],
       [     406560,      642537,     4010160,    24206400],
       [   39029760,    62968626,   156396240,  1016668800],
       [-1523854336,  -202006606,  1034363472,  -706167552]])

# np.percentile()

In [53]:
a

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [54]:
np.percentile(a,70)

64.19999999999999

# np.histogram()

In [59]:
a

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [60]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])
np.histogram(a,bins=[0,50,100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

# np.corrcoef()

In [62]:
salary=np.array([10000,20000,30000,40000,50000])
exp=np.array([1,5,3,4,2])

np.corrcoef(salary,exp)


array([[1. , 0.1],
       [0.1, 1. ]])

# np.isin()


In [63]:
a

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [68]:
items=[43,57,66]
a[np.isin(a,items)]
#np.isin(a,[31,69])

array([57, 66, 66, 43])

# np.flip()

In [69]:
a

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [70]:
np.flip(a)

array([14, 15, 43, 53, 66, 33, 95, 70, 50, 66, 57, 15, 69, 31, 51])

In [71]:
b

array([[32, 63, 93, 82],
       [77,  7, 55, 80],
       [ 3, 47, 16, 45],
       [55, 31, 49, 82],
       [96, 98, 39, 42],
       [71, 65, 89, 50]])

In [74]:
np.flip(b)

array([[50, 89, 65, 71],
       [42, 39, 98, 96],
       [82, 49, 31, 55],
       [45, 16, 47,  3],
       [80, 55,  7, 77],
       [82, 93, 63, 32]])

# np.put()

In [ ]:
#changing values

In [75]:
a

array([51, 31, 69, 15, 57, 66, 50, 70, 95, 33, 66, 53, 43, 15, 14])

In [77]:
np.put(a,[0,1],[100,101]) #changes on actual data
a

array([100, 101,  69,  15,  57,  66,  50,  70,  95,  33,  66,  53,  43,
        15,  14])

In [ ]:
#np.delete() >>>>delete items based on indices 

In [78]:
a

array([100, 101,  69,  15,  57,  66,  50,  70,  95,  33,  66,  53,  43,
        15,  14])

In [81]:
np.delete(a,[0])

array([101,  69,  15,  57,  66,  50,  70,  95,  33,  66,  53,  43,  15,
        14])

# set functions

-np.union1d
-np.intersect1d
-np.setdiff1d
-np.setxor1d
-np.in1d

In [83]:
m=np.array([1,2,3,4,5])
n=np.array([2,6,1,7,8])

In [84]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
np.intersect1d(m,n)

array([1, 2])

In [86]:
np.setdiff1d(n,m)

array([6, 7, 8])

In [88]:
np.setxor1d(m,n) #remove common items and reutrns unique

array([3, 4, 5, 6, 7, 8])

In [89]:
np.in1d(m,2) 

array([False,  True, False, False, False])

# np.clip()

In [91]:
#limit the values in an array

In [92]:
a

array([100, 101,  69,  15,  57,  66,  50,  70,  95,  33,  66,  53,  43,
        15,  14])

In [93]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 69, 25, 57, 66, 50, 70, 75, 33, 66, 53, 43, 25, 25])

# np.swapaxes()

In [94]:
#interchanges two axes of array

In [101]:
a=np.arange(12).reshape(3,4)
b=np.random.randint(50,100,12).reshape(3,4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[79 66 67 75]
 [63 79 74 69]
 [60 80 88 62]]


In [104]:
np.swapaxes([a,b],0,1)

array([[[ 0,  1,  2,  3],
        [79, 66, 67, 75]],

       [[ 4,  5,  6,  7],
        [63, 79, 74, 69]],

       [[ 8,  9, 10, 11],
        [60, 80, 88, 62]]])

# np.uniform

In [105]:
#generate random numbers for a uniform distribution
#np.uniform(low=0.0,high=1,0,size=None)

In [107]:
print(np.random.uniform(10,20,size=5))

[12.6108344  12.69530583 19.13880705 15.32945691 11.94997606]


# np.count_nonzero

In [111]:
a=np.array([0,100,5,7,8,1,2,3,0,0,0,1,0])
a

array([  0, 100,   5,   7,   8,   1,   2,   3,   0,   0,   0,   1,   0])

In [112]:
np.count_nonzero(a!=0)

8

# np.repeat

In [113]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [114]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [115]:
b

array([[79, 66, 67, 75],
       [63, 79, 74, 69],
       [60, 80, 88, 62]])

In [118]:
np.repeat(b,2)

array([79, 79, 66, 66, 67, 67, 75, 75, 63, 63, 79, 79, 74, 74, 69, 69, 60,
       60, 80, 80, 88, 88, 62, 62])

# np.any()

In [154]:
# checks if atleast one condtion is True
a=np.array([0,0,0,1,5])
np.any(a==0) #axis=0 or 1 #2D

True

In [155]:
#checks if every element meets the condtion
np.all(a>=0) # axis=0 or 1  #2D

True

# Random Modules

In [120]:
#np.sample--->float numbers only
a=np.random.sample(size=(2,3))
a

array([[0.64434348, 0.70387289, 0.14482864],
       [0.64884809, 0.2468669 , 0.17138591]])

In [ ]:
#np.random.shuffle() >>>>>>randomly shuffles the items of an array in place
#changes applied on actual array

In [127]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [130]:
np.random.shuffle(a)
print(a)

[2 1 3]


# np.random.permutation()

In [ ]:
#shuffle copy

In [133]:
r=np.array([1,2,3])
new_=np.random.permutation(r)
print(new_)

[2 1 3]


# np.random.seed()

In [136]:
print(np.random.rand(2))

[0.74233987 0.9580418 ]


In [143]:
np.random.seed(42)
print(np.random.rand(2))

[0.37454012 0.95071431]


# file handling in Numpy

In [156]:
#refers to reading from and writing to files,especially when dealing with large numeric datasets


# np.savetxt()


In [157]:
a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [159]:
#saving file
np.savetxt('sample.txt',a)
#customize
np.savetxt('output.txt',a,delimiter=',',fmt='%d')

# np.loadtxt()

In [160]:
np.loadtxt('sample.txt')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

# np.getfromtxt()

In [166]:
r=np.array([1,2,3,np.nan,5])
np.savetxt("have_missing",r)

In [170]:
#load
x=np.genfromtxt("have_missing")
data=np.nan_to_num(x)
data

array([1., 2., 3., 0., 5.])

In [172]:
#np.save()
arr=np.array([1,2,3])
np.save("myarray.npy",arr)

In [173]:
#np.load()
np.load("myarray.npy")

array([1, 2, 3])